# Generated by Django 5.2.1 on 2025-08-06 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria de Pergunta',
                'verbose_name_plural': 'Categorias de Perguntas',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado_pergunta', models.CharField(max_length=150)),
                ('tipo_pergunta', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Pergunta (Deprecated)',
                'verbose_name_plural': 'Perguntas (Deprecated)',
            },
        ),
        migrations.CreateModel(
            name='PerfilAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(default='Ativo', max_length=45)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_aluno', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_academico', models.CharField(max_length=45)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_professor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_nome', models.CharField(max_length=45)),
                ('curso_sigla', models.CharField(max_length=10)),
                ('coordenador_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='avaliacao_docente.perfilprofessor')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status_avaliacao', models.CharField(max_length=15)),
                ('professor_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_antigas', to='avaliacao_docente.perfilprofessor')),
            ],
            options={
                'verbose_name': 'Avaliação (Deprecated)',
                'verbose_name_plural': 'Avaliações (Deprecated)',
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas_antigas', to='avaliacao_docente.avaliacao')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_antigas', to='avaliacao_docente.pergunta')),
            ],
            options={
                'verbose_name': 'Avaliação-Pergunta (Deprecated)',
                'verbose_name_plural': 'Avaliações-Perguntas (Deprecated)',
            },
        ),
        migrations.CreateModel(
            name='PerguntaAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('tipo', models.CharField(choices=[('likert', 'Escala de Concordância (Likert) - Discordo totalmente / Concordo totalmente'), ('nps', 'Net Promoter Score - Escala 0 a 10 para recomendação'), ('multipla_escolha', 'Múltipla Escolha - Uma ou mais opções'), ('sim_nao', 'Sim ou Não - Resposta binária simples'), ('texto_livre', 'Resposta Aberta - Comentários livres e sugestões')], max_length=20)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('obrigatoria', models.BooleanField(default=True)),
                ('ativa', models.BooleanField(default=True)),
                ('opcoes_multipla_escolha', models.JSONField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='avaliacao_docente.categoriapergunta')),
            ],
            options={
                'verbose_name': 'Pergunta de Avaliação',
                'verbose_name_plural': 'Perguntas de Avaliação',
                'ordering': ['categoria__ordem', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField(choices=[(1, '1º Semestre'), (2, '2º Semestre'), (3, '3º Semestre'), (4, '4º Semestre'), (5, '5º Semestre'), (6, '6º Semestre'), (7, '7º Semestre'), (8, '8º Semestre'), (9, '9º Semestre'), (10, '10º Semestre')])),
            ],
            options={
                'ordering': ['-ano', '-semestre'],
                'unique_together': {('ano', 'semestre')},
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina_nome', models.CharField(max_length=100)),
                ('disciplina_sigla', models.CharField(max_length=45)),
                ('disciplina_tipo', models.CharField(choices=[('Obrigatória', 'Obrigatória'), ('Optativa', 'Optativa')], max_length=45)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='avaliacao_docente.curso')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='avaliacao_docente.perfilprofessor')),
                ('periodo_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='avaliacao_docente.periodoletivo')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionarioAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionarios_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Questionário de Avaliação',
                'verbose_name_plural': 'Questionários de Avaliação',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='RespostaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_pergunta', models.CharField(max_length=300)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_antigas', to='avaliacao_docente.perfilaluno')),
                ('avaliacao_pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_antigas', to='avaliacao_docente.avaliacaopergunta')),
            ],
            options={
                'verbose_name': 'Resposta Aluno (Deprecated)',
                'verbose_name_plural': 'Respostas Alunos (Deprecated)',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_turma', models.CharField(max_length=20, unique=True)),
                ('turno', models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino'), ('noturno', 'Noturno')], max_length=15)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('finalizada', 'Finalizada')], default='ativa', max_length=15)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='avaliacao_docente.disciplina')),
                ('periodo_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='avaliacao_docente.periodoletivo')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='avaliacao_docente.perfilprofessor')),
            ],
            options={
                'ordering': ['periodo_letivo', 'disciplina__disciplina_nome'],
                'unique_together': {('disciplina', 'periodo_letivo', 'turno')},
            },
        ),
        migrations.CreateModel(
            name='CicloAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('permite_avaliacao_anonima', models.BooleanField(default=True)),
                ('permite_multiplas_respostas', models.BooleanField(default=False)),
                ('enviar_lembrete_email', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos_criados', to=settings.AUTH_USER_MODEL)),
                ('periodo_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos_avaliacao', to='avaliacao_docente.periodoletivo')),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='avaliacao_docente.questionarioavaliacao')),
                ('turmas', models.ManyToManyField(blank=True, help_text='Selecione as turmas que devem participar desta avaliação', related_name='ciclos_avaliacao', to='avaliacao_docente.turma', verbose_name='Turmas que devem responder')),
            ],
            options={
                'verbose_name': 'Ciclo de Avaliação',
                'verbose_name_plural': 'Ciclos de Avaliação',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendente', max_length=15)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='avaliacao_docente.cicloavaliacao')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_docente', to='avaliacao_docente.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas', to='avaliacao_docente.perfilprofessor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_docente', to='avaliacao_docente.turma')),
            ],
            options={
                'verbose_name': 'Avaliação Docente',
                'verbose_name_plural': 'Avaliações Docentes',
                'ordering': ['-data_criacao'],
                'unique_together': {('ciclo', 'turma', 'professor', 'disciplina')},
            },
        ),
        migrations.CreateModel(
            name='ComentarioAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elogios', models.TextField(blank=True, verbose_name='Elogios')),
                ('sugestoes', models.TextField(blank=True, verbose_name='Sugestões')),
                ('criticas_construtivas', models.TextField(blank=True, verbose_name='Críticas Construtivas')),
                ('data_comentario', models.DateTimeField(auto_now_add=True)),
                ('anonimo', models.BooleanField(default=False)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='avaliacao_docente.avaliacaodocente')),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_avaliacoes', to='avaliacao_docente.perfilaluno')),
            ],
            options={
                'verbose_name': 'Comentário de Avaliação',
                'verbose_name_plural': 'Comentários de Avaliação',
                'ordering': ['data_comentario'],
                'unique_together': {('avaliacao', 'aluno', 'session_key')},
            },
        ),
        migrations.CreateModel(
            name='QuestionarioPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_no_questionario', models.PositiveIntegerField(default=0)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionarios', to='avaliacao_docente.perguntaavaliacao')),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='avaliacao_docente.questionarioavaliacao')),
            ],
            options={
                'verbose_name': 'Pergunta do Questionário',
                'verbose_name_plural': 'Perguntas do Questionário',
                'ordering': ['ordem_no_questionario'],
                'unique_together': {('questionario', 'pergunta')},
            },
        ),
        migrations.CreateModel(
            name='RespostaAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True)),
                ('valor_numerico', models.IntegerField(blank=True, null=True)),
                ('valor_boolean', models.BooleanField(blank=True, null=True)),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('anonima', models.BooleanField(default=False)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas_avaliacoes', to='avaliacao_docente.perfilaluno')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='avaliacao_docente.avaliacaodocente')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='avaliacao_docente.perguntaavaliacao')),
            ],
            options={
                'verbose_name': 'Resposta de Avaliação',
                'verbose_name_plural': 'Respostas de Avaliação',
                'ordering': ['data_resposta'],
                'unique_together': {('avaliacao', 'aluno', 'pergunta', 'session_key')},
            },
        ),
        migrations.CreateModel(
            name='MatriculaTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('trancada', 'Trancada'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída')], default='ativa', max_length=15)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='avaliacao_docente.perfilaluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='avaliacao_docente.turma')),
            ],
            options={
                'ordering': ['data_matricula'],
                'unique_together': {('aluno', 'turma')},
            },
        ),
        migrations.CreateModel(
            name='HorarioTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='avaliacao_docente.turma')),
            ],
            options={
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('turma', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
