# Generated by Django 5.2.1 on 2025-05-11 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno_matricula', models.CharField(max_length=45)),
                ('aluno_nome', models.CharField(max_length=100)),
                ('aluno_email', models.CharField(max_length=100)),
                ('aluno_situacao', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status_avaliacao', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diario_periodo', models.CharField(max_length=45)),
                ('ano_letivo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado_pergunta', models.CharField(max_length=150)),
                ('tipo_pergunta', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_nome', models.CharField(max_length=150)),
                ('registro_academico', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina_nome', models.CharField(max_length=100)),
                ('disciplina_sigla', models.CharField(max_length=45)),
                ('disciplina_tipo', models.CharField(max_length=45)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='avaliacao_docente.curso')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='avaliacao_docente.avaliacao')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='avaliacao_docente.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='CoordenadorCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordenadores', to='avaliacao_docente.curso')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_coordenados', to='avaliacao_docente.professor')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='avaliacao_docente.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='avaliacao_docente.professor')),
            ],
        ),
        migrations.CreateModel(
            name='DiarioProfessorDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diarios', to='avaliacao_docente.aluno')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='avaliacao_docente.diario')),
                ('professor_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diarios', to='avaliacao_docente.professordisciplina')),
            ],
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='professor_disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='avaliacao_docente.professordisciplina'),
        ),
        migrations.CreateModel(
            name='RespostaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_pergunta', models.CharField(max_length=300)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='avaliacao_docente.aluno')),
                ('avaliacao_pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='avaliacao_docente.avaliacaopergunta')),
            ],
        ),
    ]
