# Generated by Django 5.2.1 on 2025-07-08 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_nome', models.CharField(max_length=45)),
                ('curso_sigla', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diario_periodo', models.CharField(max_length=45)),
                ('ano_letivo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado_pergunta', models.CharField(max_length=150)),
                ('tipo_pergunta', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(default='Ativo', max_length=45)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_aluno', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_academico', models.CharField(max_length=45)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_professor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina_nome', models.CharField(max_length=100)),
                ('disciplina_sigla', models.CharField(max_length=45)),
                ('disciplina_tipo', models.CharField(max_length=45)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='avaliacao_docente.curso')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='avaliacao_docente.diario')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='avaliacao_docente.perfilprofessor')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='coordenador_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='avaliacao_docente.perfilprofessor'),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status_avaliacao', models.CharField(max_length=15)),
                ('professor_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='avaliacao_docente.perfilprofessor')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='avaliacao_docente.avaliacao')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='avaliacao_docente.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_pergunta', models.CharField(max_length=300)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='avaliacao_docente.perfilaluno')),
                ('avaliacao_pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='avaliacao_docente.avaliacaopergunta')),
            ],
        ),
    ]
