# Generated by Django 5.2.1 on 2025-07-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_docente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='disciplina_tipo',
            field=models.CharField(choices=[('Optativa', 'Optativa'), ('Obrigatória', 'Obrigatória')], max_length=12),
        ),
    ]
