# Generated by Django 4.2.6 on 2025-06-27 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("avaliacao_docente", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="curso",
            name="coordenador_curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cursos",
                to="avaliacao_docente.perfilprofessor",
            ),
        ),
        migrations.DeleteModel(name="PerfilCoordenador",),
        migrations.AlterField(
            model_name="perfilaluno",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfil_aluno",
                to="avaliacao_docente.user",
            ),
        ),
        migrations.AlterField(
            model_name="perfilprofessor",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfil_professor",
                to="avaliacao_docente.user",
            ),
        ),
    ]
