# Generated by Django 5.2.1 on 2025-09-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_docente', '0002_remove_comentarioavaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='codigo_turma',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
