# Generated by Django 5.2.1 on 2025-07-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_docente', '0002_alter_disciplina_disciplina_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='disciplina_tipo',
            field=models.CharField(choices=[('Obrigatória', 'Obrigatória'), ('Optativa', 'Optativa')], max_length=12),
        ),
    ]
