# Generated by Django 5.2.1 on 2025-07-12 02:37

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_docente', '0002_turma_matriculaturma_horarioturma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria de Pergunta',
                'verbose_name_plural': 'Categorias de Perguntas',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name': 'Avaliação (Deprecated)', 'verbose_name_plural': 'Avaliações (Deprecated)'},
        ),
        migrations.AlterModelOptions(
            name='avaliacaopergunta',
            options={'verbose_name': 'Avaliação-Pergunta (Deprecated)', 'verbose_name_plural': 'Avaliações-Perguntas (Deprecated)'},
        ),
        migrations.AlterModelOptions(
            name='pergunta',
            options={'verbose_name': 'Pergunta (Deprecated)', 'verbose_name_plural': 'Perguntas (Deprecated)'},
        ),
        migrations.AlterModelOptions(
            name='respostaaluno',
            options={'verbose_name': 'Resposta Aluno (Deprecated)', 'verbose_name_plural': 'Respostas Alunos (Deprecated)'},
        ),
        migrations.AlterModelManagers(
            name='perfilaluno',
            managers=[
                ('non_admin', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='perfilprofessor',
            managers=[
                ('non_admin', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='professor_disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_antigas', to='avaliacao_docente.perfilprofessor'),
        ),
        migrations.AlterField(
            model_name='avaliacaopergunta',
            name='avaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas_antigas', to='avaliacao_docente.avaliacao'),
        ),
        migrations.AlterField(
            model_name='avaliacaopergunta',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_antigas', to='avaliacao_docente.pergunta'),
        ),
        migrations.AlterField(
            model_name='respostaaluno',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_antigas', to='avaliacao_docente.perfilaluno'),
        ),
        migrations.AlterField(
            model_name='respostaaluno',
            name='avaliacao_pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_antigas', to='avaliacao_docente.avaliacaopergunta'),
        ),
        migrations.CreateModel(
            name='CicloAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('permite_avaliacao_anonima', models.BooleanField(default=True)),
                ('permite_multiplas_respostas', models.BooleanField(default=False)),
                ('enviar_lembrete_email', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos_criados', to=settings.AUTH_USER_MODEL)),
                ('periodo_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos_avaliacao', to='avaliacao_docente.periodoletivo')),
            ],
            options={
                'verbose_name': 'Ciclo de Avaliação',
                'verbose_name_plural': 'Ciclos de Avaliação',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendente', max_length=15)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_docente', to='avaliacao_docente.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas', to='avaliacao_docente.perfilprofessor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_docente', to='avaliacao_docente.turma')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='avaliacao_docente.cicloavaliacao')),
            ],
            options={
                'verbose_name': 'Avaliação Docente',
                'verbose_name_plural': 'Avaliações Docentes',
                'ordering': ['-data_criacao'],
                'unique_together': {('ciclo', 'turma', 'professor', 'disciplina')},
            },
        ),
        migrations.CreateModel(
            name='PerguntaAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('tipo', models.CharField(choices=[('likert', 'Escala de Concordância (Likert) - Discordo totalmente / Concordo totalmente'), ('nps', 'Net Promoter Score - Escala 0 a 10 para recomendação'), ('multipla_escolha', 'Múltipla Escolha - Uma ou mais opções'), ('sim_nao', 'Sim ou Não - Resposta binária simples'), ('texto_livre', 'Resposta Aberta - Comentários livres e sugestões')], max_length=20)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('obrigatoria', models.BooleanField(default=True)),
                ('ativa', models.BooleanField(default=True)),
                ('opcoes_multipla_escolha', models.JSONField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='avaliacao_docente.categoriapergunta')),
            ],
            options={
                'verbose_name': 'Pergunta de Avaliação',
                'verbose_name_plural': 'Perguntas de Avaliação',
                'ordering': ['categoria__ordem', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='QuestionarioAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionarios_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Questionário de Avaliação',
                'verbose_name_plural': 'Questionários de Avaliação',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddField(
            model_name='cicloavaliacao',
            name='questionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='avaliacao_docente.questionarioavaliacao'),
        ),
        migrations.CreateModel(
            name='ComentarioAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elogios', models.TextField(blank=True, verbose_name='Elogios')),
                ('sugestoes', models.TextField(blank=True, verbose_name='Sugestões')),
                ('criticas_construtivas', models.TextField(blank=True, verbose_name='Críticas Construtivas')),
                ('data_comentario', models.DateTimeField(auto_now_add=True)),
                ('anonimo', models.BooleanField(default=False)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_avaliacoes', to='avaliacao_docente.perfilaluno')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='avaliacao_docente.avaliacaodocente')),
            ],
            options={
                'verbose_name': 'Comentário de Avaliação',
                'verbose_name_plural': 'Comentários de Avaliação',
                'ordering': ['data_comentario'],
                'unique_together': {('avaliacao', 'aluno', 'session_key')},
            },
        ),
        migrations.CreateModel(
            name='QuestionarioPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_no_questionario', models.PositiveIntegerField(default=0)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionarios', to='avaliacao_docente.perguntaavaliacao')),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='avaliacao_docente.questionarioavaliacao')),
            ],
            options={
                'verbose_name': 'Pergunta do Questionário',
                'verbose_name_plural': 'Perguntas do Questionário',
                'ordering': ['ordem_no_questionario'],
                'unique_together': {('questionario', 'pergunta')},
            },
        ),
        migrations.CreateModel(
            name='RespostaAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True)),
                ('valor_numerico', models.IntegerField(blank=True, null=True)),
                ('valor_boolean', models.BooleanField(blank=True, null=True)),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('anonima', models.BooleanField(default=False)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas_avaliacoes', to='avaliacao_docente.perfilaluno')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='avaliacao_docente.avaliacaodocente')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='avaliacao_docente.perguntaavaliacao')),
            ],
            options={
                'verbose_name': 'Resposta de Avaliação',
                'verbose_name_plural': 'Respostas de Avaliação',
                'ordering': ['data_resposta'],
                'unique_together': {('avaliacao', 'aluno', 'pergunta', 'session_key')},
            },
        ),
    ]
