# Generated by Django 5.2.1 on 2025-07-14 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_docente', '0003_categoriapergunta_alter_avaliacao_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='perfilaluno',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='perfilprofessor',
            managers=[
            ],
        ),
    ]
