# Generated by Django 5.2.1 on 2025-09-26 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_docente', '0003_aumentar_codigo_turma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perguntaavaliacao',
            options={'ordering': ['categoria__ordem'], 'verbose_name': 'Pergunta de Avaliação', 'verbose_name_plural': 'Perguntas de Avaliação'},
        ),
        migrations.RemoveField(
            model_name='perguntaavaliacao',
            name='ordem',
        ),
    ]
