# Generated by Django 5.2.1 on 2025-09-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_docente', '0004_alter_perguntaavaliacao_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notificacao_erros', models.EmailField(blank=True, help_text='E-mail para receber notificações de erros do sistema (quando DEBUG=False).', max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='avaliacaopergunta',
            name='avaliacao',
        ),
        migrations.RemoveField(
            model_name='avaliacaopergunta',
            name='pergunta',
        ),
        migrations.RemoveField(
            model_name='respostaaluno',
            name='avaliacao_pergunta',
        ),
        migrations.RemoveField(
            model_name='respostaaluno',
            name='aluno',
        ),
        migrations.DeleteModel(
            name='Avaliacao',
        ),
        migrations.DeleteModel(
            name='Pergunta',
        ),
        migrations.DeleteModel(
            name='AvaliacaoPergunta',
        ),
        migrations.DeleteModel(
            name='RespostaAluno',
        ),
    ]
