# Generated by Django 5.2.1 on 2025-09-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_docente', '0005_configuracaosite_remove_avaliacaopergunta_avaliacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='metodo_envio_email',
            field=models.CharField(choices=[('api', 'API (Recomendado para Vercel)'), ('smtp', 'SMTP (Para desenvolvimento local/outros hosts)')], default='api', help_text="Escolha o método para enviar e-mails. 'API' é necessário para a Vercel.", max_length=10),
        ),
    ]
