# Generated by Django 4.2.6 on 2025-07-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avaliacao_docente", "0005_alter_perfilaluno_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cicloavaliacao",
            name="turmas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Selecione as turmas que devem participar desta avaliação",
                related_name="ciclos_avaliacao",
                to="avaliacao_docente.turma",
                verbose_name="Turmas que devem responder",
            ),
        ),
    ]
