"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv, RepositoryEnv
import os

# Carrega o arquivo .env explicitamente da pasta raiz do projeto
DOTENV_FILE = Path(__file__).resolve().parent.parent / '.env'
if DOTENV_FILE.exists():
    # Usa um repositório customizado para o decouple ler o arquivo
    custom_repo = RepositoryEnv(DOTENV_FILE)
    config.repository = custom_repo


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool, default=False)

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rolepermissions",
    "social_django",
    "avaliacao_docente.apps.AvaliacaoDocenteConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Para servir arquivos estáticos
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "avaliacao_docente.middleware.ClearMessageMiddleware",  # Limpa mensagens antigas
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "setup.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "social_django.context_processors.backends",
                "social_django.context_processors.login_redirect",
            ],
        },
    },
]

WSGI_APPLICATION = "setup.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Banco de dados PostgreSQL e esta hospedado na Vercel
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="5432"),
        "OPTIONS": {
            "sslmode": "require",
        },
    }
}


# Use para desenvolvimento rapido
# DATABASES = {
#    "default": {
#        "ENGINE": "django.db.backends.sqlite3",
#        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
#    }
# }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Cuiaba"

USE_L10N = True

USE_TZ = True
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Configuração de Logging para enviar e-mails de erro
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'mail_admins_dynamic': {
            'level': 'ERROR',
            'class': 'avaliacao_docente.utils.DynamicAdminEmailHandler',
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['mail_admins_dynamic'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}



# ============ CONFIGURAÇÕES DE AUTENTICAÇÃO ============

# Backends de autenticação - SUAP OAuth2 + Django padrão
AUTHENTICATION_BACKENDS = (
    "suap_backend.backends.SuapOAuth2",
    "django.contrib.auth.backends.ModelBackend",
)

# URLs de redirecionamento
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

# ============ CONFIGURAÇÕES SOCIAL AUTH (SUAP) ============

# Chaves de API do SUAP (devem ser definidas nas variáveis de ambiente)
SOCIAL_AUTH_SUAP_KEY = config(
    "SOCIAL_AUTH_SUAP_KEY",
)
SOCIAL_AUTH_SUAP_SECRET = config(
    "SOCIAL_AUTH_SUAP_SECRET",
)

# Configurações do pipeline de autenticação social
SOCIAL_AUTH_PIPELINE = (
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "setup.settings.allow_all_users",  # Permite todos os usuários
    "social_core.pipeline.social_auth.social_user",
    "social_core.pipeline.user.get_username",
    "social_core.pipeline.user.create_user",
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.social_auth.load_extra_data",
    "avaliacao_docente.auth_pipeline.apply_suap_user_type",  # Aplica role e perfis via tipo_usuario
    "social_core.pipeline.user.user_details",
)


# Configurações de sessão para o social auth
SOCIAL_AUTH_SUAP_SCOPE = []  # Deixe vazio para evitar erro de invalid_scope
SOCIAL_AUTH_LOGIN_REDIRECT_URL = "/"
SOCIAL_AUTH_NEW_USER_REDIRECT_URL = "/"
SOCIAL_AUTH_LOGIN_ERROR_URL = "/accounts/login/"
SOCIAL_AUTH_RAISE_EXCEPTIONS = False
SOCIAL_AUTH_BACKEND_ERROR_URL = "/accounts/login/"
SOCIAL_AUTH_ALLOWED_REDIRECT_HOSTS = ["127.0.0.1", "localhost"]
SOCIAL_AUTH_SUAP_REDIRECT_URI = "http://127.0.0.1:8000/complete/suap/"

# Logging para inspecionar o fluxo de autenticação SUAP
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        "suap_backend": {"handlers": ["console"], "level": "INFO"},
        "social": {"handlers": ["console"], "level": "INFO"},
    },
}


# ============ CONFIGURAÇÕES DE ROLES ============

ROLEPERMISSIONS_MODULE = "setup.roles"  # Define o módulo de permissões de função

# ============ CONFIGURAÇÕES ESPECÍFICAS PARA VERCEL ============

# Configurações de segurança para produção
if not DEBUG:
    # Headers de segurança
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

    # HTTPS em produção
    SECURE_SSL_REDIRECT = False  # Vercel já gerencia HTTPS

# Configuração para lidar com headers do Vercel
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Configurações de timeout para Vercel (máximo 10 segundos para hobby plan)
if "VERCEL" in os.environ:
    # Configurações específicas do Vercel
    DATABASES["default"]["CONN_MAX_AGE"] = 0  # Não usar conexões persistentes

    # Log para debugging no Vercel
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
            },
        },
        "loggers": {
            "django": {
                "handlers": ["console"],
                "level": "INFO",
            },
        },
    }


def allow_all_users(strategy, details, user=None, *args, **kwargs):
    # Pipeline que não bloqueia nenhuma credencial retornada pelo SUAP
    return
